MODE: "test"  # train or test

DEVICE: "cuda:0"  # cuda:x or cpu

IS_GRADCAM: True

DATASET:
    TEST:
        PATH: "test"
        NUMBER_OF_SAMPLE: 4  # batch size
        NUM_WORKERS: 0
        AUGMENTATIONS:
            Resize: (256, 256, p=1)

TEST_INFO:  # Please refer to the yaml_doc.md
    WEIGHT_PATH: "./logs/resnet18_cls02_20210628_235545/models/resnet18_BestModel_cls02_ep0015_acc0.85621_loss0.65517.pth"

NOTIFICATION:
    SLACK:
        WEBHOOK_URL: ""
        CHANNEL:
        END_MESSAGE: ""
