mode: "test"  # train or test

dataset:
    test:
        number_of_sample: 4  # batch size
        num_workers: 0
        path: "test"
        augmentations:
            Resize: (256, 256, p=1)

test_info:  # Please refer to the yaml_doc.md
    wight_path: "./logs/resnet18_cls02_20210605_230315/models/resnet18_cls02_ep0001.pth"
