MODE: "train"  # train or test

DEVICE: "cuda:0"  # cuda:x or cpu

DATASET:
    TRAIN:
        PATH: "train"
        NUMBER_OF_SAMPLE: 4  # batch size
        NUM_WORKERS: 0
        AUGMENTATIONS:
            Resize: (256, 256, p=1)
            HorizontalFlip: (p=0.5)
    VAL:
        PATH: "val"
        AUGMENTATIONS:
            Resize: (256, 256, p=1)

TRAIN_INFO:  # Please refer to the configs/README.md
    MAXIMUM_EPOCH: 40
    SAVE_INTERVAL: 5
    MODEL: "resnet18"
    CRITERION: CrossEntropyLoss()
    OPTIMIZER: SGD(model.parameters(), lr=1.0e-4, momentum=0.9)
    SCHEDULER: CosineAnnealingWarmUpRestarts(optimizer, T_0=50, eta_max=1.0e-2, T_up=10)

NOTIFICATION:
    SLACK:
        WEBHOOK_URL: ""
        CHANNEL:
        END_MESSAGE: "[Windows Server]: Learning is complete."
