mode: "train"  # train or test

dataset:
    train:
        path: "train"
        number_of_sample: 4  # batch size
        num_workers: 0
        augmentations:
            Resize: (256, 256, p=1)
            HorizontalFlip: (p=0.5)
    val:
        path: "val"
        augmentations:
            Resize: (256, 256, p=1)

train_info:  # Please refer to the configs/README.md
    maximum_epoch: 100
    save_interval: 5
    model: "resnet18"
    criterion: CrossEntropyLoss()
    optimizer: SGD(model.parameters(), lr=1.0e-4, momentum=0.9)
    scheduler: CosineAnnealingWarmUpRestarts(optimizer, T_0=50, eta_max=1.0e-2, T_up=10)
